version: '3'
services:
  redis-server: 
    image: 'redis'
  node-app:
    build: ./countries-backend/
    ports:
      - "5000:5000"
  front-end:
    build: ./countries-frontend/
    ports:
      - "8080:80"
    